### ISSUE TITLE
Could you update to latest mod_wsgi version?

### ISSUE THREAD

**Issue by jonathanmorgan** [conda-forge/mod_wsgi-feedstock#9]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Could you please update this to the latest version of mod_wsgi (4.9.0)?

**Comment by ReimarBauer** [comment]
@jonathanmorgan not seen the bot has found problems, will have a look.
